#!/usr/bin/env python3
"""Summary-table generators (spec §5.3). Subcommands:
  queue    -> assessments/QUEUE.md   (once; hand-curated afterwards; --force to regen)
  ranking  -> assessments/RANKING.md (regenerated from assessments/*.metrics.json)
  patch    -> rewrite ONLY the status cell of matching GAME_FORMATS.md rows"""
import glob, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
GF = os.path.join(REPO, "GAME_FORMATS.md")
ASSESS = os.path.join(REPO, "assessments")
# Families kept out of the queue with a reason (spec §1 + calibration refs)
EXCLUDE = {"cleoftp": "reference — already fan-ported (`../cleopatra`)"}

_ROW = re.compile(r"^\| (.+?) \| `(\w+)` \| (.+?) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \|\s*$")
_CLONE = re.compile(r"clone of `(\w+)`")


def parse_rows(text):
    rows = {}
    for line in text.splitlines():
        m = _ROW.match(line)
        if not m:
            continue
        title, setname, fmt, rel, size, genre, dc, status = m.groups()
        cm = _CLONE.search(rel)
        rows[setname] = {"title": title, "format": fmt, "parent": cm.group(1) if cm else None,
                         "size": size, "genre": genre, "dc_port": dc, "status": status}
    return rows


def families(rows):
    fams = {}
    for s, r in rows.items():
        fams.setdefault(r["parent"] or s, []).append(s)
    return fams


def in_scope(fams, rows):
    """Spec §1: family in scope iff NO member has an official DC port, minus EXCLUDE."""
    return {rep: members for rep, members in fams.items()
            if rep not in EXCLUDE
            and not any(rows[m]["dc_port"].startswith("Yes") for m in members)}


def load_sidecars():
    out = {}
    for p in glob.glob(os.path.join(ASSESS, "*.metrics.json")):
        with open(p) as fh:
            sc = json.load(fh)
        out[sc["set"]] = sc
    return out


def queue(force=False):
    path = os.path.join(ASSESS, "QUEUE.md")
    if os.path.isfile(path) and not force:
        sys.exit("QUEUE.md exists (hand-curated) — use --force to regenerate")
    rows = parse_rows(open(GF).read())
    fams = families(rows)
    scope = in_scope(fams, rows)
    lines = ["# Assessment queue", "",
             "Generated by `tools/assess/gen_tables.py queue` from `GAME_FORMATS.md`; "
             "hand-curated afterwards (representative overrides, ordering).", "",
             "| Representative | Family members | Genre | Size | Status |", "|---|---|---|---|---|"]
    def key(rep):
        g = rows[rep]["genre"]
        return (0 if "★" in g else (2 if "⚠" in g else 1), g, rep)
    for rep in sorted(scope, key=key):
        members = ", ".join(f"`{m}`" for m in sorted(scope[rep]))
        r = rows[rep]
        lines.append(f"| `{rep}` — {r['title']} | {members} | {r['genre']} | {r['size']} | pending |")
    excl = ", ".join(f"`{k}` ({v})" for k, v in EXCLUDE.items())
    lines += ["", f"Excluded beyond official DC ports: {excl}.", ""]
    open(path, "w").write("\n".join(lines))
    print(f"QUEUE.md: {len(scope)} families")


def ranking():
    scs = load_sidecars()
    scored = [s for s in scs.values() if s.get("scores")]
    parked = [s for s in scs.values() if s.get("gate")]
    unscored = [s for s in scs.values() if not s.get("scores") and not s.get("gate")]
    scored.sort(key=lambda s: -s["scores"]["final"])
    lines = ["# Portability ranking", "",
             "Generated by `tools/assess/gen_tables.py ranking` from `assessments/*.metrics.json`. "
             "Do not edit by hand.", "",
             "| # | Game | Set | Final | Tier | Mem | Stream | Guts | Ctrl | Sim |",
             "|---|---|---|---|---|---|---|---|---|---|"]
    for i, s in enumerate(scored, 1):
        sc = s["scores"]
        lines.append(f"| {i} | {s['title']} | [`{s['set']}`]({s['set']}.md) | **{sc['final']}** "
                     f"| {sc['tier']} | {sc['memory']} | {sc['streaming']} | {sc['guts']} "
                     f"| {sc['controls']} | {sc['similarity']} |")
    if parked:
        lines += ["", "## Parked", ""] + [
            f"- [`{s['set']}`]({s['set']}.md) — {s['gate']}" for s in parked]
    if unscored:
        lines += ["", "## Awaiting controls research", ""] + [
            f"- [`{s['set']}`]({s['set']}.md)" for s in unscored]
    open(os.path.join(ASSESS, "RANKING.md"), "w").write("\n".join(lines) + "\n")
    print(f"RANKING.md: {len(scored)} scored, {len(parked)} parked, {len(unscored)} unscored")


def patch_text(text, sidecars, clones):
    out = []
    for line in text.splitlines(keepends=True):
        m = _ROW.match(line.rstrip("\n"))
        if m:
            setname = m.group(2)
            cell = None
            if setname in sidecars:
                sc = sidecars[setname]
                if sc.get("scores"):
                    cell = (f"**{sc['scores']['final']}** {sc['scores']['tier']} · "
                            f"[assessment](assessments/{setname}.md)")
                elif sc.get("gate"):
                    cell = f"parked {sc['gate'].split()[0]} · [notes](assessments/{setname}.md)"
            elif setname in clones and clones[setname] in sidecars:
                rep = clones[setname]
                cell = f"see [`{rep}`](assessments/{rep}.md)"
            if cell:
                head = line.rstrip("\n").rsplit("|", 2)[0]
                line = f"{head}| {cell} |\n"
        out.append(line)
    return "".join(out)


def patch():
    text = open(GF).read()
    rows = parse_rows(text)
    clones = {s: r["parent"] for s, r in rows.items() if r["parent"]}
    open(GF, "w").write(patch_text(text, load_sidecars(), clones))
    print("GAME_FORMATS.md patched")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "queue":
        queue("--force" in sys.argv)
    elif cmd == "ranking":
        ranking()
    elif cmd == "patch":
        patch()
    else:
        sys.exit("usage: gen_tables.py queue|ranking|patch")
