#!/usr/bin/env python3
"""Summary-table generators (spec §5.3). Subcommands:
  queue    -> assessments/QUEUE.md   (once; hand-curated afterwards; --force to regen)
  ranking  -> assessments/RANKING.md (regenerated from assessments/*.metrics.json)
  patch    -> rewrite ONLY the status cell of matching GAME_FORMATS.md rows"""
import glob, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
GF = os.path.join(REPO, "GAME_FORMATS.md")
ASSESS = os.path.join(REPO, "assessments")
# Families kept out of the queue with a reason (spec §1 + calibration refs)
EXCLUDE = {"cleoftp": "reference — already fan-ported (`../cleopatra`)"}

_ROW = re.compile(r"^\| (.+?) \| `(\w+)` \| (.+?) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \|\s*$")
_CLONE = re.compile(r"clone of `(\w+)`")


def parse_rows(text):
    rows = {}
    for line in text.splitlines():
        m = _ROW.match(line)
        if not m:
            continue
        title, setname, fmt, rel, size, genre, dc, status = m.groups()
        cm = _CLONE.search(rel)
        rows[setname] = {"title": title, "format": fmt, "parent": cm.group(1) if cm else None,
                         "size": size, "genre": genre, "dc_port": dc, "status": status}
    return rows


def families(rows):
    fams = {}
    for s, r in rows.items():
        # ponytail: self-key orphan clones whose parent is absent (f355→f355dlx, pokasuka→manicpnc)
        parent_key = r["parent"] if r["parent"] and r["parent"] in rows else s
        fams.setdefault(parent_key, []).append(s)
    return fams


def in_scope(fams, rows):
    """Spec §1: family in scope iff NO member has an official DC port, minus EXCLUDE."""
    return {rep: members for rep, members in fams.items()
            if rep not in EXCLUDE
            and not any(rows[m]["dc_port"].startswith("Yes") for m in members)}


def load_sidecars():
    out = {}
    for p in glob.glob(os.path.join(ASSESS, "*.metrics.json")):
        with open(p) as fh:
            sc = json.load(fh)
        out[sc["set"]] = sc
    return out


def queue(force=False):
    path = os.path.join(ASSESS, "QUEUE.md")
    if os.path.isfile(path) and not force:
        sys.exit("QUEUE.md exists (hand-curated) — use --force to regenerate")
    rows = parse_rows(open(GF).read())
    fams = families(rows)
    scope = in_scope(fams, rows)
    lines = ["# Assessment queue", "",
             "Generated by `tools/assess/gen_tables.py queue` from `GAME_FORMATS.md`; "
             "hand-curated afterwards (representative overrides, ordering).", "",
             "Representative default = MAME parent set; during hand-curation prefer the newest "
             "revision in the game's original region (spec §1) and note overrides here.", "",
             "| Representative | Family members | Genre | Size | Status |", "|---|---|---|---|---|"]
    def key(rep):
        g = rows[rep]["genre"]
        return (0 if "★" in g else (2 if "⚠" in g else 1), g, rep)
    for rep in sorted(scope, key=key):
        members = ", ".join(f"`{m}`" for m in sorted(scope[rep]))
        r = rows[rep]
        lines.append(f"| `{rep}` — {r['title']} | {members} | {r['genre']} | {r['size']} | pending |")
    excl = ", ".join(f"`{k}` ({v})" for k, v in EXCLUDE.items())
    lines += ["", f"Excluded beyond official DC ports: {excl}.", ""]
    open(path, "w").write("\n".join(lines))
    print(f"QUEUE.md: {len(scope)} families")


# Coverage the capture actually reached (set by the assessing agent per RUNBOOK's
# representativeness check). title/calibration = metrics are lower bounds -> flagged.
COVERAGE_FLAG = {"demo": "demo", "title": "title ⚠", "calibration": "cal ⚠"}


def coverage_flag(sc):
    return COVERAGE_FLAG.get(sc.get("capture", {}).get("coverage"), "?")


def battery_of(sc):
    # Sidecar provenance: which battery version measured this family. Scores are
    # only comparable within a version (re-assessment rule, kb §6/§11).
    return "v" + sc.get("versions", {}).get("battery", "?")


def _mb(b):
    return "0" if b == 0 else f"{b / (1 << 20):.1f} MB"


def region_work(sc, region):
    """Informational 'work bytes' per region — what a port must fix to fit.
    Semantics differ deliberately (the point of the v7/v8/v9 re-keys):
      main: content ABOVE the 16 MB line (absolute pointers pin position ->
            these bytes need relocation or trimming) = nz_above_cap.
      aram: content VOLUME beyond 2 MB (banks relocate freely, v7 proof ->
            only excess volume is work: downsample/ADPCM/stream).
      vram: FB-masked fit beyond 8 MB (textures are TA-relative, v8 ->
            excess volume is work: VQ-compress/mip-drop/page).
    '?' = keying fields absent (pre-v6/v7/v8 sidecar) and the address peak
    can't prove 0; a sub-cap peak does prove 0 (volume <= address)."""
    m = sc["memory"][region]
    if region == "main":
        b = m.get("nz_above_cap")
        return "?" if b is None else _mb(b)
    cap = 2 << 20 if region == "aram" else 8 << 20
    if region == "aram":
        fit = m.get("content_total")
    else:
        ct, fb = m.get("content_total"), m.get("fb_bytes")
        fit = ct + 2 * fb if ct is not None and fb is not None else None
    if fit is not None:
        return _mb(max(0, fit - cap))
    return "0" if m["peak"] <= cap else "?"


def ranking():
    scs = load_sidecars()
    scored = [s for s in scs.values() if s.get("scores")]
    parked = [s for s in scs.values() if s.get("gate")]
    unscored = [s for s in scs.values() if not s.get("scores") and not s.get("gate")]
    scored.sort(key=lambda s: -s["scores"]["final"])
    lines = ["# Portability ranking", "",
             "Generated by `tools/assess/gen_tables.py ranking` from `assessments/*.metrics.json`. "
             "Do not edit by hand. Coverage ⚠ = capture never reached the demo "
             "(title/calibration idle) — memory/streaming figures are lower bounds. "
             "Battery = the measuring battery version (`versions.battery`); scores are only "
             "comparable within a version — pre-v6 main figures are stale per the "
             "re-assessment rule (kb §11). Main>16MB / VRAM>8MB / ARAM>2MB = informational "
             "'work bytes', not scored: what a port must fix per region — main is content "
             "above the cap line (absolute pointers: relocate/trim), vram is FB-masked fit "
             "beyond budget (VQ-compress/page), aram is content volume beyond budget "
             "(downsample/stream); positions don't matter for vram/aram (v7/v8 rulings). "
             "? = not measured by that sidecar's battery version.", "",
             "| # | Game | Set | Final | Tier | Battery | Coverage | Mem | Main>16MB | VRAM>8MB | ARAM>2MB | Stream | Guts | Ctrl | Sim |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for i, s in enumerate(scored, 1):
        sc = s["scores"]
        lines.append(f"| {i} | {s['title']} | [`{s['set']}`]({s['set']}.md) | **{sc['final']}** "
                     f"| {sc['tier']} | {battery_of(s)} | {coverage_flag(s)} | {sc['memory']} | {region_work(s, 'main')} "
                     f"| {region_work(s, 'vram')} | {region_work(s, 'aram')} "
                     f"| {sc['streaming']} | {sc['guts']} | {sc['controls']} | {sc['similarity']} |")
    if parked:
        lines += ["", "## Parked", ""] + [
            f"- [`{s['set']}`]({s['set']}.md) — {s['gate']} · {battery_of(s)} · coverage: {coverage_flag(s)}"
            for s in parked]
    if unscored:
        lines += ["", "## Awaiting controls research", ""] + [
            f"- [`{s['set']}`]({s['set']}.md) · {battery_of(s)}" for s in unscored]
    open(os.path.join(ASSESS, "RANKING.md"), "w").write("\n".join(lines) + "\n")
    print(f"RANKING.md: {len(scored)} scored, {len(parked)} parked, {len(unscored)} unscored")


def patch_text(text, sidecars, clones):
    out = []
    for line in text.splitlines(keepends=True):
        m = _ROW.match(line.rstrip("\n"))
        if m:
            setname = m.group(2)
            cell = None
            if setname in sidecars:
                sc = sidecars[setname]
                if sc.get("scores"):
                    cell = (f"**{sc['scores']['final']}** {sc['scores']['tier']} · "
                            f"[assessment](assessments/{setname}.md)")
                elif sc.get("gate"):
                    cell = f"parked {sc['gate'].split()[0]} · [notes](assessments/{setname}.md)"
            elif setname in clones and clones[setname] in sidecars:
                rep = clones[setname]
                cell = f"see [`{rep}`](assessments/{rep}.md)"
            if cell:
                head = line.rstrip("\n").rsplit("|", 2)[0]
                line = f"{head}| {cell} |\n"
        out.append(line)
    return "".join(out)


def patch():
    text = open(GF).read()
    rows = parse_rows(text)
    clones = {s: r["parent"] for s, r in rows.items() if r["parent"]}
    open(GF, "w").write(patch_text(text, load_sidecars(), clones))
    print("GAME_FORMATS.md patched")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "queue":
        queue("--force" in sys.argv)
    elif cmd == "ranking":
        ranking()
    elif cmd == "patch":
        patch()
    else:
        sys.exit("usage: gen_tables.py queue|ranking|patch")
